#
# This file was created by Xilinx Vitis tool.
#


#
# tools
#

RM = rm -f
RMDIR = rm -rf



#
# variables
#


#
# primary build targets
#

all: package

package:
	-@echo Package not supported, if the system project is in Emulation Target, and only Baremetal Or Embedded Linux Applications present

clean:
	$(RMDIR) ./package.build
	${RMDIR} package

.PHONY: all package clean


