#ifndef SSM2603_H
#define SSM2603_H

#define CODEC_LADCIN_ADDR				0x00
#define CODEC_LADCIN_LRINBOTH_MASK		0x100 // High Byte
#define CODEC_LADCIN_LINMUTE_MASK		0x80
#define CODEC_LADCIN_LINVOL_MASK		0x3F

#define CODEC_RADCIN_ADDR				0x01
#define CODEC_RADCIN_RLINBOTH_MASK		0x100 // High Byte
#define CODEC_RADCIN_RINMUTE_MASK		0x80
#define CODEC_RADCIN_RINVOL_MASK		0x3F

#define CODEC_LDACOUT_ADDR				0x02
#define CODEC_LDACOUT_LRHPBOTH_MASK		0x100 // High Byte
#define CODEC_LDACOUT_LHPVOL_MASK		0x7F

#define CODEC_RDACOUT_ADDR				0x03
#define CODEC_RDACOUT_RLHPBOTH_MASK		0x100 // High Byte
#define CODEC_RDACOUT_RHPVOL_MASK		0x7F

#define CODEC_ANAPATH_ADDR				0x04
#define CODEC_ANAPATH_SIDETONE_ATT_MASK	0xC0
#define CODEC_ANAPATH_SIDETONE_EN_MASK	0x20
#define CODEC_ANAPATH_DACSEL_MASK		0x10
#define CODEC_ANAPATH_BYPASS_MASK		0x08
#define CODEC_ANAPATH_INSEL_MASK		0x04
#define CODEC_ANAPATH_MUTEMIC_MASK		0x02
#define CODEC_ANAPATH_MICBOOST_MASK		0x01

#define CODEC_DIGPATH_ADDR				0x05
#define CODEC_DIGPATH_HPOR_MASK			0x10
#define CODEC_DIGPATH_DACMU_MASK		0x08
#define CODEC_DIGPATH_DEEMPH_MASK		0x06
#define CODEC_DIGPATH_ADCHPF_MASK		0x01

#define CODEC_PWR_ADDR					0x06
#define CODEC_PWR_PWROFF_MASK			0x80
#define CODEC_PWR_CLKOUT_MASK			0x40
#define CODEC_PWR_OSC_MASK				0x20
#define CODEC_PWR_OUT_MASK				0x10
#define CODEC_PWR_DAC_MASK				0x08
#define CODEC_PWR_ADC_MASK				0x04
#define CODEC_PWR_MIC_MASK				0x02
#define CODEC_PWR_LINEIN_MASK			0x01

#define CODEC_DIGIF_ADDR				0x07
#define CODEC_DIGIF_BCLKINV_MASK		0x80
#define CODEC_DIGIF_MS_MASK				0x40
#define CODEC_DIGIF_LRSWAP_MASK			0x20
#define CODEC_DIGIF_LRP_MASK			0x10
#define CODEC_DIGIF_WL_MASK				0x0C
#define CODEC_DIGIF_FORMAT_MASK			0x03

#define CODEC_SAMPLE_ADDR				0x08
#define CODEC_SAMPLE_CLKODIV2_MASK		0x80
#define CODEC_SAMPLE_CLKDIV2_MASK		0x40
#define CODEC_SAMPLE_SR_MASK			0x3C
#define CODEC_SAMPLE_BOSR_MASK			0x02
#define CODEC_SAMPLE_USB_MASK			0x01

#define CODEC_ACTIVE_ADDR				0x09
#define CODEC_ACTIVE_MASK				0x01

#define CODEC_SWRESET_ADDR				0x0F
#define CODEC_SWRESET_HB_MASK			0x100 // High Byte
#define CODEC_SWRESET_LB_MASK			0xFF

#define CODEC_ALCCTRL1_ADDR				0x10
#define CODEC_ALCCTRL1_ALCSEL_HB_MASK	0x100 // High Byte
#define CODEC_ALCCTRL1_ALCSEL_LB_MASK	0x80
#define CODEC_ALCCTRL1_MAXGAIN_MASK		0x70
#define CODEC_ALCCTRL1_ALCL_MASK		0x0F

#define CODEC_ALCCTRL2_ADDR				0x11
#define CODEC_ALCCTRL2_DCY_MASK			0xF0
#define CODEC_ALCCTRL2_ATK_MASK			0x0F

#define CODEC_NSGATE_ADDR				0x12
#define CODEC_NSGATE_NGTH_MASK			0xF8
#define CODEC_NSGATE_NGG_MASK			0x06
#define CODEC_NSGATE_NGAT_MASK			0x01

#endif
