# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hannes/Entwicklung/synthesizer/FPGA/audio_station/audio_station.srcs/sources_1/bd/audio_station_overview/ip/audio_station_overview_processing_system7_0_0/audio_station_overview_processing_system7_0_0.xci
# IP: The module: 'audio_station_overview_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hannes/Entwicklung/synthesizer/FPGA/audio_station/audio_station.srcs/sources_1/bd/audio_station_overview/ip/audio_station_overview_processing_system7_0_0/audio_station_overview_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_station_overview_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hannes/Entwicklung/synthesizer/FPGA/audio_station/audio_station.srcs/sources_1/bd/audio_station_overview/ip/audio_station_overview_processing_system7_0_0/audio_station_overview_processing_system7_0_0.xci
# IP: The module: 'audio_station_overview_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hannes/Entwicklung/synthesizer/FPGA/audio_station/audio_station.srcs/sources_1/bd/audio_station_overview/ip/audio_station_overview_processing_system7_0_0/audio_station_overview_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_station_overview_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
