# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Zybo_Z7_Master.xdc

# Block Designs: bd/audio_station_overview/audio_station_overview.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_station_overview || ORIG_REF_NAME==audio_station_overview} -quiet] -quiet

# IP: bd/audio_station_overview/ip/audio_station_overview_processing_system7_0_0/audio_station_overview_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_station_overview_processing_system7_0_0 || ORIG_REF_NAME==audio_station_overview_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio_station_overview/ip/audio_station_overview_rst_ps7_0_125M_0/audio_station_overview_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_station_overview_rst_ps7_0_125M_0 || ORIG_REF_NAME==audio_station_overview_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/audio_station_overview/ip/audio_station_overview_AudioStation_0_3/audio_station_overview_AudioStation_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_station_overview_AudioStation_0_3 || ORIG_REF_NAME==audio_station_overview_AudioStation_0_3} -quiet] -quiet

# IP: bd/audio_station_overview/ip/audio_station_overview_axi_interconnect_0_0/audio_station_overview_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_station_overview_axi_interconnect_0_0 || ORIG_REF_NAME==audio_station_overview_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/audio_station_overview/ip/audio_station_overview_xlconcat_0_0/audio_station_overview_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_station_overview_xlconcat_0_0 || ORIG_REF_NAME==audio_station_overview_xlconcat_0_0} -quiet] -quiet

# IP: bd/audio_station_overview/ip/audio_station_overview_auto_pc_0/audio_station_overview_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_station_overview_auto_pc_0 || ORIG_REF_NAME==audio_station_overview_auto_pc_0} -quiet] -quiet

# XDC: bd/audio_station_overview/audio_station_overview_ooc.xdc
